"""2

Revision ID: 39e1abaadfec
Revises: ec14ccb056c3
Create Date: 2025-02-20 22:27:41.888139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e1abaadfec'
down_revision: Union[str, None] = 'ec14ccb056c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('tests_user_id_fkey', 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'users', ['owner_id'], ['id'])
    op.drop_column('tests', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key('tests_user_id_fkey', 'tests', 'users', ['user_id'], ['id'])
    op.drop_column('tests', 'owner_id')
    # ### end Alembic commands ###
