"""4

Revision ID: d10b228a3499
Revises: 67c87e80c28c
Create Date: 2025-02-21 18:33:48.783381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd10b228a3499'
down_revision: Union[str, None] = '67c87e80c28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('image_data', postgresql.BYTEA(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'image_data')
    # ### end Alembic commands ###
